[#ftl]
<title> Blog Hedviky D. </title>
    <br><br>
    <h1 class="display-5 fw-bold text-body-emphasis">Vítejte!</h1><br><br>
    <p class="lead">Vítejte na blogu Hedviky D. Zde najdete články o všem možném, co mě zajímá. </p><br><br>
    <hr class="my-4"><br><br>
    <h2>Nejnovější články</h2><br><br>
    <h2>${post.title?no_esc}</h2><br>
    <h3>${post.perex?no_esc}</h3><br>
    <h5>${post.author} on ${post.published?date}</h5><br>
    <p>${post.body?no_esc}</p><br><br>

